name: Bicep-GitHubActionsTemplate-Build
on:
  push:
     branches: 
       - 'releases/*' 
       - 'main' 
       - '!releases/old*' 
       - '!releases/poc*'
env:
  ServiceConnectionName : 'ALZPipelineConnection'
  resourceGroupName : 'bicep-rg'
  templateFile : 'main.bicep'
  RunNumber : '$(Build.BuildNumber)'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: $resourceGroupName
        template: $templateFile
        parameters: 'storagePrefix=mystore   storageSKU=Standard_LRS'
        failOnStdErr: false
